fyrkat/ledger/models.py
# -*- coding: utf-8 -*-
"""Ledger models."""
import datetime as dt
import enum

from fyrkat.user.models import User

from fyrkat.database import (
    Column,
    Model,
    SurrogatePK,
    db,
    reference_col,
    relationship,
)
from sqlalchemy_utils import CurrencyType, Currency
from sqlalchemy import desc


class TransactionCategoryType(enum.Enum):

    TRANSPORTATION = "TRANSPORTATION"
    DINING = "DINING"
    LUNCH = "LUNCH"
    FAMILY = "FAMILY"
    HOME = "HOME"
    SAVINGS = "SAVINGS"
    BOATING = "BOATING"
    SUMMER_HOUSE = "SUMMER HOUSE"
    TRAVELLING = "TRAVELLING"
    SPORTS = "SPORTS"
    GAMING = "GAMING"
    CLOTHES = "CLOTHES"
    GROCERIES = "GROCERIES"
    MUSIC = "MUSIC"
    GADGETS = "GADGETS"
    LOVE = "LOVE"
    PARTY = "PARTY"

class Account(SurrogatePK, Model):

    __tablename__ = "accounts"

    account_name = Column(db.String(500))

    user_id = Column(db.Integer, db.ForeignKey('users.id'))
    user = relationship("User", backref="accounts")

    # eg. IBAN
    account_reference = Column(db.String(50))

    # eg. OPI
    external_entity = Column(db.String(50))
    external_id = Column(db.String(500), unique=True, nullable=True)

    def __repr__(self):
        """Represent instance as a unique string."""
        return f"Account {self.id}"

class Transaction(SurrogatePK, Model):

    __tablename__ = "transactions"

    account_id = Column(db.Integer, db.ForeignKey('accounts.id'))
    account = relationship("Account", backref="transactions")

    external_entity = Column(db.String(50))
    external_id = Column(db.String(500), unique=True, nullable=True)

    payment_date = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)

    beneficiary = Column(db.String(500))
    message = Column(db.String(500))
    amount = db.Column(db.Numeric)

    # Recommendation engine
    base_joy_scale = Column(db.Integer, nullable=True)
    transaction_category = db.Column(db.Enum(TransactionCategoryType))


    @classmethod
    def uncategorised_for_user(kls, user):
        return Transaction.query.join(Account).join(User).filter(User.id == user.id).filter(Transaction.base_joy_scale == None).all()

    @classmethod
    def daterange_for_user(kls, user, start, end):
        return Transaction.query.join(Account).join(User).filter(User.id == user.id).filter(Transaction.payment_date.between(start, end)).all()

    @classmethod
    def uncategorised_daterange_for_user(kls, user, start, end):
        return Transaction.query.join(Account).join(User).filter(User.id == user.id).filter(Transaction.payment_date.between(start, end)).filter(Transaction.base_joy_scale == None).all()

    @classmethod
    def latest_for_user(kls, user):
        return Transaction.query.join(Account).join(User).filter(User.id == user.id).order_by(desc(Transaction.payment_date)).first()

fyrkat/ledger/forms.py
# -*- coding: utf-8 -*-
"""Public forms."""
from flask_wtf import FlaskForm
from wtforms import RadioField, HiddenField, StringField, SelectMultipleField, FileField
from wtforms.widgets import ListWidget, CheckboxInput
from wtforms.validators import DataRequired, InputRequired

class MultiCheckboxField(SelectMultipleField):
	widget			= ListWidget(prefix_label=False)
	option_widget	= CheckboxInput()

class AccountForm(FlaskForm):
    """Rating form."""
    account_name = StringField("Account Name")


class PSDAccountForm(FlaskForm):
    accounts_to_import = MultiCheckboxField('Accounts to import', choices=[])

fyrkat/ledger/__init__.py
# -*- coding: utf-8 -*-
"""The ledger modules."""
from . import views  # noqa
from . import admin  # noqa

fyrkat/ledger/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from fyrkat.ledger.models import Account, Transaction
from fyrkat.jobs.psd2fetch import PSD2Fetch
from .forms import AccountForm, PSDAccountForm
from .models import Account
from fyrkat.extensions import db

blueprint = Blueprint("ledger", __name__, url_prefix="/ledger", static_folder="../static")

@blueprint.route("/create-account", methods=["GET", "POST"])
@login_required
def create_account():
    account = Account()
    success = False

    if request.method == 'POST':
        form = AccountForm(request.form)
        if form.validate():
            account = Account(account_name=form.data["account_name"], user=current_user)
            db.session.add(account)
            db.session.commit()
            success = True
            return redirect(url_for("user.home"))
        else:
            flash_errors(form)
            
    form = AccountForm(obj=account)
    return render_template("ledger/create-account.html", form=form)


@blueprint.route("/import-from-psd", methods=["GET", "POST"])
@login_required
def import_from_psd():

    if request.method == 'POST':
        form = PSDAccountForm(request.form)

        # TODO handle if this is just one string, or a list of strings
        accounts_to_import = [request.form["accounts_to_import"]]

        total_categorized = 0
        total_imported = 0

        for account_to_import in accounts_to_import:

            [imported, categorized] = PSD2Fetch().import_transactions(account_to_import, current_user.id)
            total_categorized += categorized
            total_imported += imported

        flash(f"Imported {total_imported} transactions from PSD2 api 📦", "success")
        flash(f"Used Machine Learning magic to categorize {total_categorized} transactions 🧙‍♂️", "success")

        return redirect(url_for("user.home"))
    else: 
        form = PSDAccountForm()
        accounts = PSD2Fetch().get_accounts()
        choices = []

        for account in accounts:
            choices += [(account["accountId"], account["name"])]

        form.accounts_to_import.choices = choices

        return render_template("ledger/psd-create-account.html", accounts=accounts, form=form)

fyrkat/templates/ledger/create-account.html
{% extends "layout.html" %}
{% block content %}
    <div class="container">
        <h1>Let's create an account!</h1>
        <div>
            <form id="account-create-form" class="form form-account-create" method="POST" action="" role="form">
                {{ form.csrf_token }}
                {{ form.account_name.label }} {{ form.account_name(size=20) }}
                <p><input class="btn btn-primary" type="submit" value="Create new standalone account"></p>
            </form>
        </div>
        <div>
            <a href="{{url_for('ledger.import_from_psd')}}" class="btn btn-primary btn-lg active btn-dark" role="button" aria-pressed="true">PSD2 MAGIC API FOR OP 🧙‍♂️ </a>
        </div>
    </div>
{% endblock %}

fyrkat/templates/ledger/psd-create-account.html
{% extends "layout.html" %}
{% block content %}
    <div class="container">
        <h1>Let's import accounts :)</h1>
        <div>
            <form id="account-create-form" class="form form-account-create" method="POST" action="" role="form">
                {% for field in form %}
                    <p>{{ field.label }} {{ field }}</p>
                {% endfor %}
                {{ form.csrf_token }}
                <p><input class="btn btn-primary" type="submit" value="Import accounts 🚛"></p>
            </form>
        </div>
        <div>
            <a href="{{url_for('user.home')}}" class="btn btn-primary btn-lg active btn-dark" role="button" aria-pressed="true">Nope... </a>
        </div>
    </div>
{% endblock %}