fyrkat/dashboard/views.py
# -*- coding: utf-8 -*-
"""Dashboard views."""
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import login_required, current_user
from fyrkat.dashboard.forms import RatingForm
from fyrkat.ledger.models import Transaction, Account
from fyrkat.user.models import User
from fyrkat.utils import flash_errors
from fyrkat.extensions import db
from collections import defaultdict
from fyrkat.jobs.recommendations import give_recommendation

blueprint = Blueprint("dashboard", __name__, url_prefix="/dashboard", static_folder="../static")

@login_required
@blueprint.route("/rating/<transaction_id>", methods=["GET", "POST"])
def rating(transaction_id):
    """Add new rating."""
    transaction = Transaction.get_by_id(transaction_id)

    if transaction.account.user.id != current_user.id:
        flash("BACKOFF, PUNK! Not authorized.", "error")
        return redirect(url_for(".insights_new"))

    form = RatingForm(transaction)

    if form.validate_on_submit():
        transaction.base_joy_scale = form.rating.data
        transaction.save()
        flash(f"Rated ✅", "success")
        return redirect(url_for(".rate_randon_unrated"))
    else:
        flash_errors(form)
    return render_template("dashboard/rating.html", form=form, amount=round(abs(transaction.amount), 2), ben=transaction.beneficiary)

@login_required
@blueprint.route("/rating-random", methods=["GET"])
def rate_randon_unrated():
    transaction = next(iter(Transaction.uncategorised_for_user(current_user)), None)
    if not transaction:
        flash(f"Wow, you're all done, no more transactions to classify 💥", "success")
        return redirect(url_for("user.home"))
        
    return redirect(url_for('.rating', transaction_id=transaction.id))

@login_required
@blueprint.route("/insights/<year>-<month>", methods=["GET"])
def insights(year, month):
    """Insights view."""
    y = int(year)
    m = int(month)
    start = f'{year}-{m:02}-01'
    end = f'{year}-{m+1:02}-01'
    transactions = Transaction.daterange_for_user(current_user, start, end)
    uncategorized_transactions = Transaction.uncategorised_daterange_for_user(current_user, start, end)
    total_amount = round(sum(map(lambda x: abs(x.amount), transactions)), 2)
    grouped = defaultdict(list)
    for transaction in transactions: grouped[transaction.base_joy_scale].append(transaction)
    grouped_fractions = defaultdict(float)
    for k in grouped.keys(): grouped_fractions[k] = round(sum(map(lambda x: abs(x.amount), grouped[k]))/total_amount, 2)
    return render_template("dashboard/insights.html", 
            start=start, end=end, total=total_amount, 
            uncategorized_transactions=uncategorized_transactions, 
            grouped=grouped_fractions, 
            recommendations=give_recommendation(current_user.id))

@login_required
@blueprint.route("/insights/new", methods=["GET"])
def insights_new():
    latest_date = Transaction.latest_for_user(current_user).payment_date
    month = latest_date.strftime("%m")
    year = latest_date.strftime("%Y")
    return insights(year, month)

fyrkat/ledger/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from fyrkat.ledger.models import Account, Transaction
from fyrkat.jobs.psd2fetch import PSD2Fetch
from .forms import AccountForm, PSDAccountForm
from .models import Account
from fyrkat.extensions import db

blueprint = Blueprint("ledger", __name__, url_prefix="/ledger", static_folder="../static")

@blueprint.route("/create-account", methods=["GET", "POST"])
@login_required
def create_account():
    account = Account()
    success = False

    if request.method == 'POST':
        form = AccountForm(request.form)
        if form.validate():
            account = Account(account_name=form.data["account_name"], user=current_user)
            db.session.add(account)
            db.session.commit()
            success = True
            return redirect(url_for("user.home"))
        else:
            flash_errors(form)
            
    form = AccountForm(obj=account)
    return render_template("ledger/create-account.html", form=form)


@blueprint.route("/import-from-psd", methods=["GET", "POST"])
@login_required
def import_from_psd():

    if request.method == 'POST':
        form = PSDAccountForm(request.form)

        # TODO handle if this is just one string, or a list of strings
        accounts_to_import = [request.form["accounts_to_import"]]

        total_categorized = 0
        total_imported = 0

        for account_to_import in accounts_to_import:

            [imported, categorized] = PSD2Fetch().import_transactions(account_to_import, current_user.id)
            total_categorized += categorized
            total_imported += imported

        flash(f"Imported {total_imported} transactions from PSD2 api 📦", "success")
        flash(f"Used Machine Learning magic to categorize {total_categorized} transactions 🧙‍♂️", "success")

        return redirect(url_for("user.home"))
    else: 
        form = PSDAccountForm()
        accounts = PSD2Fetch().get_accounts()
        choices = []

        for account in accounts:
            choices += [(account["accountId"], account["name"])]

        form.accounts_to_import.choices = choices

        return render_template("ledger/psd-create-account.html", accounts=accounts, form=form)

fyrkat/user/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from fyrkat.database import db
from fyrkat.utils import flash_errors

from fyrkat.ledger.models import Transaction

blueprint = Blueprint("user", __name__, url_prefix="/users", static_folder="../static")


@blueprint.route("/")
@login_required
def home():
    """List members."""
    uncategorized_transactions = Transaction.uncategorised_for_user(current_user)

    if not current_user.accounts:
        return render_template("users/start.html")
    else:
        return render_template("users/home.html", uncategorized_transactions=uncategorized_transactions)

@blueprint.route("/demodata", methods=["GET", "POST"])
@login_required
def demodata():
    """Show form for adding demo data."""
    from fyrkat.jobs.intervention import InterventionCall
    from fyrkat.jobs.classification import classify_transaction_xgboost
    from fyrkat.ledger.models import Transaction
    from fyrkat.user.forms import DemoForm
    from datetime import datetime

    form = DemoForm(request.form)
    if form.validate_on_submit():
        account = current_user.accounts[0]
        # Create the transaction
        date = datetime.now()
        amount = -1.0*float(form.amount.data)
        beneficiary = form.beneficiary.data
        message = ""

        tx = Transaction(
            account=account, 
            payment_date=date,
            amount=amount,
            message=message,
            beneficiary=beneficiary
            )
        db.session.add(tx)
        db.session.commit()

        # Run classification
        tx.base_joy_scale = classify_transaction_xgboost(tx.beneficiary)
        db.session.commit()

        if (tx.base_joy_scale == 0):
            # If the added transaction was unpleasant, fire the intervention
            intervention = InterventionCall(current_user.id)
            intervention.call(beneficiary, amount)
        flash("Data added!", "success")
        return redirect(url_for("public.home"))
    else:
        flash_errors(form)
    
    return render_template("users/demodata.html", form=form)

fyrkat/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('public.home')}}">log in</a> or
            <a href="{{ url_for('public.register') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}

fyrkat/templates/footer.html
<footer>
  <small>
  <ul class="company">
    <li>© Alakantti Team</li>
  </ul>

    <ul class="footer-nav">

      <li><a href="{{ url_for('public.about') }}">About</a></li>

      <li><a href="mailto:smaisidoro@gmail.com">Contact</a></li>
    </ul>
  </small>
</footer>

fyrkat/templates/layout.html
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en">
  <!--<![endif]-->
  <head>
    <meta charset="utf-8" />

    <link rel="shortcut icon" href="{{static_url_for('static', filename='build/img/favicon.ico') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">
    
    <title>
      {% block page_title %} 
      Fyrkat
       {% endblock %}
    </title>
    <meta
      name="description"
      content="{% block meta_description %}{% endblock %}"
    />
    <meta name="author" content="{% block meta_author %}{% endblock %}" />

    <!-- Mobile viewport optimized: h5bp.com/viewport -->
    <meta name="viewport" content="width=device-width" />

    <link
      rel="stylesheet"
      type="text/css"
      href="{{ static_url_for('static', filename='build/main_css.bundle.css') }}"
    />

    {% block css %}{% endblock %}
  </head>
  <body class="{% block body_class %}{% endblock %}">
    {% block body %} {% with form=form %} {% include "nav.html" %} {% endwith %}

    <header>{% block header %}{% endblock %}</header>

    <main role="main">
      {% with messages = get_flashed_messages(with_categories=true) %} {% if
      messages %}
      <div class="row">
        <div class="col-md-12">
          {% for category, message in messages %}
          <div class="alert alert-{{ category }}">
            <a class="close" title="Close" href="#" data-dismiss="alert"
              >&times;</a
            >
            {{ message }}
          </div>
          <!-- end .alert -->
          {% endfor %}
        </div>
        <!-- end col-md -->
      </div>
      <!-- end row -->
      {% endif %} {% endwith %} {% block content %}{% endblock %}
    </main>

    {% include "footer.html" %}

    <!-- JavaScript at the bottom for fast page loading -->
    <script src="{{ static_url_for('static', filename='build/main_js.bundle.js') }}"></script>
    {% block js %}{% endblock %}
    <!-- end scripts -->
    {% endblock %}
  </body>
</html>

fyrkat/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <a class="navbar-brand" href="{{ url_for('public.home') }}">
      <div class="imgCont"><img src="{{static_url_for('static', filename='build/img/FLOGO.png') }}"/></div>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('public.home') }}">Home
          <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item active">
          <a class="nav-link" href="{{ url_for('dashboard.insights_new') }}">New insights 🤔
            <span class="sr-only">(current)</span>
          </a>
      </li>
      <li class="nav-item active">
          <a class="nav-link" href="{{ url_for('dashboard.rate_randon_unrated') }}">Categorize transactions ❓
            <span class="sr-only">(current)</span>
          </a>
      </li>
      <li class="nav-item active">
          <a class="nav-link" href="{{ url_for('ledger.create_account') }}">Create or import new account 📦
            <span class="sr-only">(current)</span>
          </a>
      </li>
    </ul>
    {% if current_user and current_user.is_authenticated %}
    <ul class="navbar-nav my-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('user.home') }}">Logged in as {{ current_user.username }}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('public.logout') }}">
          <i class="fa fa-sign-out"></i>
        </a>
      </li>
    </ul>
    {% elif form %}
    <form class="form-inline" id="loginForm" method="POST" action="/" role="login">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
      <div class="input-group mb-2 mr-sm-2">
        {{ form.username(placeholder="Username", class_="form-control mr-sm-1 my-auto") }} {{ form.password(placeholder="Password",
        class_="form-control mr-sm-1 my-auto") }}
        <button class="btn btn-light btn-primary m-auto" type="submit">Login</button>
      </div>
    </form>
    <ul class="navbar-nav my-auto">
      <li class="nav-item">
        <a class="nav-link navbar-text" href="{{ url_for('public.register') }}">Create account</a>
      </li>
    </ul>
    {% endif %}
  </div><!-- /.navbar-collapse -->
</nav>